import { PrismaClient, Role, Plan, SubscriptionStatus } from '@prisma/client';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database...');

  // Clean existing data
  await prisma.notification.deleteMany();
  await prisma.aIRequestLog.deleteMany();
  await prisma.message.deleteMany();
  await prisma.chat.deleteMany();
  await prisma.document.deleteMany();
  await prisma.task.deleteMany();
  await prisma.project.deleteMany();
  await prisma.payment.deleteMany();
  await prisma.subscription.deleteMany();
  await prisma.refreshToken.deleteMany();
  await prisma.user.deleteMany();

  // Create Users
  const adminPassword = await bcrypt.hash('admin123', 10);
  const userPassword = await bcrypt.hash('user123', 10);

  const admin = await prisma.user.create({
    data: {
      email: 'admin@skillforge.ai',
      password: adminPassword,
      name: 'Admin Forge',
      role: Role.ADMIN,
      isVerified: true,
      credits: 9999,
      subscriptions: {
        create: {
          plan: Plan.PREMIUM,
          status: SubscriptionStatus.ACTIVE,
          startDate: new Date(),
        }
      }
    }
  });

  const user = await prisma.user.create({
    data: {
      email: 'user@skillforge.ai',
      password: userPassword,
      name: 'Alex Developer',
      role: Role.USER,
      isVerified: true,
      credits: 50,
      subscriptions: {
        create: {
          plan: Plan.FREE,
          status: SubscriptionStatus.ACTIVE,
          startDate: new Date(),
        }
      }
    }
  });

  console.log('Users created:', { adminEmail: admin.email, userEmail: user.email });

  // Create Projects & Tasks for User
  const project = await prisma.project.create({
    data: {
      name: 'Career Transition Plan',
      description: 'Step-by-step tasks to land a software engineering job in 2026.',
      userId: user.id,
      tasks: {
        createMany: {
          data: [
            {
              title: 'Build SkillForge AI portfolio project',
              description: 'Complete backend APIs and frontend mock integrations.',
              status: 'IN_PROGRESS',
              priority: 'HIGH',
              dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000)
            },
            {
              title: 'Optimize LinkedIn Profile using AI optimizer',
              description: 'Incorporate keywords generated by SkillForge optimizer.',
              status: 'TODO',
              priority: 'MEDIUM',
              dueDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000)
            },
            {
              title: 'Do mock coding interview practice',
              description: 'Practice 3 medium algorithms with answer evaluation.',
              status: 'DONE',
              priority: 'MEDIUM',
              dueDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000)
            }
          ]
        }
      }
    }
  });

  console.log('Projects and Tasks seeded.');

  // Create AI Request Logs
  await prisma.aIRequestLog.createMany({
    data: [
      { userId: user.id, toolUsed: 'AI Chat Assistant', creditsUsed: 1, status: 'SUCCESS' },
      { userId: user.id, toolUsed: 'ATS Resume Score', creditsUsed: 2, status: 'SUCCESS' },
      { userId: user.id, toolUsed: 'Mock Interview Practice', creditsUsed: 3, status: 'SUCCESS' },
      { userId: user.id, toolUsed: 'AI Study Planner', creditsUsed: 2, status: 'SUCCESS' },
    ]
  });

  // Create Notifications
  await prisma.notification.createMany({
    data: [
      { userId: user.id, title: 'Welcome to SkillForge AI!', message: 'Explore the AI Workspace and start generating career roadmaps.', read: false },
      { userId: user.id, title: 'Credit Bonus Added', message: 'You have been awarded 10 free AI credits to try out the mock interview features.', read: true }
    ]
  });

  console.log('AI Logs and Notifications seeded successfully.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
